import { InstanceNameField } from "../shell/index.js";
import {useEffect,useState,type FormEvent} from "react";
import {Button,ConfirmDangerDialog,ErrorState,FormField,TextField} from "@sarmg/admin-ui";
import {useAdminApplication,errorRequestId} from "../shell/index.js";
import {CURRENT_API_PREFIX,isDevice,isOperation,isOperations,type Command,type DeviceInfo,type Operation,type Snapshot,type Ticket,currentErrorEnvelope} from "./api";
import {configFields} from "./config-fields";
import {TicketPanel} from "./DeviceRegistrationDialog";
const states:Record<string,string>={unknown:"尚未核对",awaiting_restart:"配置已保存，等待管理员重启",pending_verification:"配置已读取，运行时生效待验证",drift_detected:"实际配置与已保存修订不同，请核对冲突"};
const tasks:Record<string,string>={pending:"排队中",running:"执行中",succeeded:"执行已完成",failed:"执行失败",unknown:"结果不确定",resolved:"已人工核对",dead_letter:"执行已拒绝"};
export function AgentWorkspace({device,changed,ticket:initialTicket,page}:{device:DeviceInfo;changed():void;ticket:Ticket|null;page:string}){
 const{client,notify}=useAdminApplication();const[ticket,setTicket]=useState(initialTicket);const[operations,setOperations]=useState<Operation[]>([]);
 const[busy,setBusy]=useState(false);const[failure,setFailure]=useState<{message:string;requestId?:string}|null>(null);const[confirm,setConfirm]=useState<{title:string;description:string;run():Promise<void>}|null>(null);
 const[baseline,setBaseline]=useState<Snapshot|null>(device.snapshot);const[draft,setDraft]=useState<Record<string,string>>(device.snapshot?.fields??{});const[remove,setRemove]=useState<string[]>([]);const[preview,setPreview]=useState<Command|null>(null);
 const base=`${CURRENT_API_PREFIX}/sunshine/devices/${device.id}`;
 useEffect(()=>{if(!baseline&&device.snapshot){setBaseline(device.snapshot);setDraft(device.snapshot.fields)}},[baseline,device.snapshot]);
 useEffect(()=>{setTicket(initialTicket)},[initialTicket]);
 useEffect(()=>{const controller=new AbortController();let active=true;async function load(){try{const values=await client.request(base+"/tasks",isOperations,{signal:controller.signal});if(active)setOperations(values)}catch(error){if(active)setFailure({message:"任务列表暂时不可用",requestId:errorRequestId(error)})}}
 void load();const timer=setInterval(()=>void load(),2000);return()=>{active=false;controller.abort();clearInterval(timer)}},[base,client]);
 async function perform(action:()=>Promise<void>){if(busy)return;setBusy(true);setFailure(null);try{await action();changed()}catch(error){setFailure({message:currentErrorEnvelope(error)?.code==="conflict"?"配置或设备状态发生冲突，请刷新后核对。":"操作未能确认，请检查任务记录，勿直接重复重启。",requestId:errorRequestId(error)})}finally{setBusy(false)}}
 async function submit(command:Command){await perform(async()=>{const operation=await client.request(base+"/tasks",isOperation,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(command)});setOperations(values=>[operation,...values.filter(value=>value.operation_id!==operation.operation_id)]);notify("任务已持久化，等待 Agent 执行。");setPreview(null)})}
 const blocked=busy||device.revoked||!device.registered||operations.some(operation=>["pending","running","unknown"].includes(operation.state));
 function difference(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!baseline)return;const set:Record<string,string|number|boolean>={};for(const field of configFields){const value=draft[field.key]??"";if(!remove.includes(field.key)&&value!==""&&value!==baseline.fields[field.key]){set[field.key]=field.kind==="integer"?Number(value):field.boolean?value==="true":value}}
 const deleted=remove.filter(key=>key in baseline.fields);if(!Object.keys(set).length&&!deleted.length){notify("没有需要保存的变更");return}setPreview({kind:"patch_config",expected_revision:baseline.revision,set,remove:deleted,restart_policy:"manual"})}
 function loadLatest(){if(device.snapshot){setBaseline(device.snapshot);setDraft(device.snapshot.fields);setRemove([]);setPreview(null)}}
 return <div className="sarmg-instance-detail sunshine-workspace">
 {failure&&<ErrorState requestId={failure.requestId}>{failure.message}</ErrorState>}
 {page==="设备状态"&&<section className="sarmg-content-panel"><h2>设备状态</h2><dl><dt>Agent</dt><dd>{device.revoked?"凭据已撤销":!device.registered?(device.pairing_pending?"等待配对":"配对已取消"):device.agent_online?"在线":"离线"}</dd><dt>Sunshine 接口</dt><dd>{device.sunshine_reachable===null?"未知":device.sunshine_reachable?"可访问":"不可访问"}</dd><dt>配置状态</dt><dd>{states[device.configuration_state]??device.configuration_state}</dd></dl>
 <p>Agent 在线不等于 Sunshine 正常；配置保存或重启响应不证明运行时已生效。</p>
 <form onSubmit={event=>{event.preventDefault();const name=String(new FormData(event.currentTarget).get("name")??"").trim();void perform(async()=>{await client.request(base,isDevice,{method:"PATCH",body:JSON.stringify({name})})})}}><FormField label="实例名称"><InstanceNameField key={device.name} name="name" defaultValue={device.name} required  /></FormField><Button type="submit" disabled={busy}>保存名称</Button></form>
 {device.pairing_pending&&!device.registered&&!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:"取消配对",description:"配对码将立即失效。实例记录会保留；如需重新配对，请新建实例。",run:()=>perform(async()=>{await client.request(base+"/pairing",(value):value is undefined=>value===undefined,{method:"DELETE"});setTicket(null)})})}>取消配对</Button>}
 {device.registered&&!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:"撤销设备凭据",description:"将断开 Agent 并永久禁止该设备凭据。执行中的任务可能变为不确定；如需重新注册，请新建设备。",run:()=>perform(async()=>{await client.request(base+"/revoke",(value):value is undefined=>value===undefined,{method:"POST"});setTicket(null)})})}>撤销设备凭据</Button>}
 {ticket&&device.pairing_pending&&!device.registered&&!device.revoked&&<TicketPanel ticket={ticket}/>}</section>}
 {page==="Sunshine 配置"&&<section className="sarmg-content-panel"><h2>Sunshine 配置</h2><p>受管字段由 Manager 统一管理。本地同时编辑可能发生竞争；修订检查不是 Sunshine 原子并发控制。</p>
 <div className="sarmg-actions"><Button disabled={blocked} onClick={()=>void submit({kind:"read_config"})}>从 Agent 读取配置</Button><Button disabled={!device.snapshot||busy} onClick={loadLatest}>使用最新配置（丢弃未提交编辑）</Button></div>
 {baseline&&device.snapshot&&baseline.revision!==device.snapshot.revision&&<p role="alert">配置修订已变化。请核对最新配置后重新编辑，不能覆盖其他修改。</p>}
 {baseline?<form onSubmit={difference}><p>未列出的配置保留不变；命令、文件路径和敏感网络设置不开放远程修改。</p>
 {configFields.map(field=><div key={field.key} className="sunshine-config-field"><FormField label={`${field.label} (${field.key})`}>{field.kind==="select"?<select aria-label={`${field.label} (${field.key})`} value={draft[field.key]??""} disabled={busy||remove.includes(field.key)} onChange={event=>setDraft({...draft,[field.key]:event.target.value})}><option value="">未显式设置</option>{field.options?.map(value=><option key={value} value={value}>{value}</option>)}</select>:<TextField type={field.kind==="integer"?"number":"text"} min={field.min} max={field.max} step={1} maxLength={field.kind==="text"?64:undefined} pattern={field.kind==="text"?".{1,32}":undefined} value={draft[field.key]??""} disabled={busy||remove.includes(field.key)} onChange={event=>setDraft({...draft,[field.key]:event.target.value})}/>}</FormField>
 <label><input type="checkbox" checked={remove.includes(field.key)} disabled={busy||!(field.key in baseline.fields)} onChange={event=>setRemove(event.target.checked?[...remove,field.key]:remove.filter(key=>key!==field.key))}/>恢复默认（删除显式设置）</label></div>)}
 <Button type="submit" disabled={blocked}>预览变更</Button></form>:<p>尚未读取配置。设备注册后可提交读取任务；离线任务会等待连接。</p>}
 {preview?.kind==="patch_config"&&<section aria-label="变更差异预览"><h3>变更差异预览</h3><table><thead><tr><th>字段</th><th>原值</th><th>新值</th></tr></thead><tbody>{[...Object.keys(preview.set),...preview.remove].map(key=><tr key={key}><td>{key}</td><td>{baseline?.fields[key]??"默认"}</td><td>{preview.remove.includes(key)?"恢复默认":String(preview.set[key])}</td></tr>)}</tbody></table><p>只保存配置，不自动重启。</p><Button disabled={blocked} onClick={()=>void submit(preview)}>确认保存配置</Button><Button onClick={()=>setPreview(null)}>返回编辑</Button></section>}
 <p>{states[device.configuration_state]}</p><Button disabled={blocked||!device.snapshot||!device.capabilities?.restart_allowed} onClick={()=>setConfirm({title:"确认重启 Sunshine",description:"重启可能中断正在进行的串流。必须由管理员明确授权；Agent 管理进程保持独立。重启后仍可能需要人工验证运行时生效。",run:async()=>{if(device.snapshot)await submit({kind:"restart",expected_revision:device.snapshot.revision,administrator_confirmed:true})}})}>重启 Sunshine</Button>{!device.capabilities?.restart_allowed&&<p>Agent 本机尚未授权受控重启。</p>}</section>}
 {page==="任务记录"&&<section className="sarmg-content-panel"><h2>任务记录</h2>{!operations.length&&<p>暂无任务</p>}{operations.map(operation=><article key={operation.operation_id}><h3>{operation.action} · {tasks[operation.state]}</h3><code>{operation.operation_id}</code>{operation.result&&<p>结果：{operation.result.kind} {operation.result.reason??""}</p>}{operation.result?.kind==="conflict"&&<p role="alert">配置冲突，请重新读取并核对差异。</p>}{operation.reconciliation&&<p>Agent 核对证据：{operation.reconciliation.kind} {operation.reconciliation.reason??""}。证据不会自动代替管理员确认。</p>}{operation.state==="unknown"&&<div className="sarmg-actions">{[["confirmed_succeeded","确认已成功"],["confirmed_failed","确认未成功"],["unable_to_confirm","仍无法确认"]].map(([resolution,label])=><Button key={resolution} disabled={busy} onClick={()=>setConfirm({title:label,description:"请先核对实际设备状态。此操作只记录人工结论，不会重跑任务。",run:()=>perform(async()=>{const updated=await client.request(`${CURRENT_API_PREFIX}/sunshine/operations/${operation.operation_id}/resolve`,isOperation,{method:"POST",body:JSON.stringify({resolution})});setOperations(values=>values.map(value=>value.operation_id===updated.operation_id?updated:value))})})}>{label}</Button>)}</div>}</article>)}</section>}
 {confirm&&<ConfirmDangerDialog title={confirm.title} description={confirm.description} pending={busy} onClose={()=>setConfirm(null)} onConfirm={()=>{const action=confirm;setConfirm(null);void action.run()}}/>}
 </div>;
}
